/* tslint:disable */
/* eslint-disable */
/**
 * Justina Io
 * OpenApi documentaciÃ³n para app de justina
 *
 * The version of the OpenAPI document: 1.0
 * Contact: justina@ejemplo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MedicoRequest
 */
export interface MedicoRequest {
    /**
     * First name of the doctor
     * @type {string}
     * @memberof MedicoRequest
     */
    nombre?: string;
    /**
     * Last name of the doctor
     * @type {string}
     * @memberof MedicoRequest
     */
    apellido?: string;
    /**
     * Phone number of the doctor
     * @type {string}
     * @memberof MedicoRequest
     */
    telefono?: string;
    /**
     * Province where the doctor practices
     * @type {string}
     * @memberof MedicoRequest
     */
    provincia?: string;
    /**
     * City or town where the doctor practices
     * @type {string}
     * @memberof MedicoRequest
     */
    localidad?: string;
    /**
     * Medical license number of the doctor
     * @type {string}
     * @memberof MedicoRequest
     */
    licencia?: string;
    /**
     * ID of the doctor's specialty
     * @type {number}
     * @memberof MedicoRequest
     */
    especialidad?: number;
    /**
     * List of IDs of insurance providers the doctor accepts
     * @type {Array<number>}
     * @memberof MedicoRequest
     */
    financiadores?: Array<number>;
}

/**
 * Check if a given object implements the MedicoRequest interface.
 */
export function instanceOfMedicoRequest(value: object): value is MedicoRequest {
    return true;
}

export function MedicoRequestFromJSON(json: any): MedicoRequest {
    return MedicoRequestFromJSONTyped(json, false);
}

export function MedicoRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MedicoRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'nombre': json['nombre'] == null ? undefined : json['nombre'],
        'apellido': json['apellido'] == null ? undefined : json['apellido'],
        'telefono': json['telefono'] == null ? undefined : json['telefono'],
        'provincia': json['provincia'] == null ? undefined : json['provincia'],
        'localidad': json['localidad'] == null ? undefined : json['localidad'],
        'licencia': json['licencia'] == null ? undefined : json['licencia'],
        'especialidad': json['especialidad'] == null ? undefined : json['especialidad'],
        'financiadores': json['financiadores'] == null ? undefined : json['financiadores'],
    };
}

export function MedicoRequestToJSON(value?: MedicoRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'nombre': value['nombre'],
        'apellido': value['apellido'],
        'telefono': value['telefono'],
        'provincia': value['provincia'],
        'localidad': value['localidad'],
        'licencia': value['licencia'],
        'especialidad': value['especialidad'],
        'financiadores': value['financiadores'],
    };
}

