/* tslint:disable */
/* eslint-disable */
/**
 * Justina Io
 * OpenApi documentaciÃ³n para app de justina
 *
 * The version of the OpenAPI document: 1.0
 * Contact: justina@ejemplo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PasswordRequest
 */
export interface PasswordRequest {
    /**
     * 
     * @type {string}
     * @memberof PasswordRequest
     */
    password: string;
}

/**
 * Check if a given object implements the PasswordRequest interface.
 */
export function instanceOfPasswordRequest(value: object): value is PasswordRequest {
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function PasswordRequestFromJSON(json: any): PasswordRequest {
    return PasswordRequestFromJSONTyped(json, false);
}

export function PasswordRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasswordRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'password': json['password'],
    };
}

export function PasswordRequestToJSON(value?: PasswordRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'password': value['password'],
    };
}

